#!/bin/sh
# =====================
# Calico — Asterisk entrypoint
# Reads env vars, writes config files, starts Asterisk
# =====================

set -e

CONFIG_DIR=/etc/asterisk

echo "Calico Asterisk: generating config from environment..."

# =====================
# sip.conf
# =====================
cat > "$CONFIG_DIR/sip.conf" << EOF
; Auto-generated by entrypoint.sh — do not edit manually

[general]
context=calico
bindport=${ASTERISK_SIP_PORT:-5062}
bindaddr=0.0.0.0
nat=force_rport,comedia
qualify=yes
language=en

; Oak — Cisco 7940G line 1
[oak-line1]
type=friend
secret=${ASTERISK_LINE1_SECRET}
host=dynamic
context=calico
callerid="${ASTERISK_LINE1_DISPLAYNAME:-Oak}" <${ASTERISK_LINE1_NUMBER:-2001}>
disallow=all
allow=ulaw
allow=alaw

EOF

# Append any additional extensions from ASTERISK_EXTENSION_N_* vars
i=1
while true; do
  NAME=$(eval echo "\$ASTERISK_EXTENSION_${i}_NAME")
  NUMBER=$(eval echo "\$ASTERISK_EXTENSION_${i}_NUMBER")
  SECRET=$(eval echo "\$ASTERISK_EXTENSION_${i}_SECRET")
  DISPLAY=$(eval echo "\$ASTERISK_EXTENSION_${i}_DISPLAYNAME")
  if [ -z "$NAME" ] || [ -z "$NUMBER" ] || [ -z "$SECRET" ]; then
    break
  fi
  cat >> "$CONFIG_DIR/sip.conf" << EOF
; Extension $i: $NAME
[$NAME]
type=friend
secret=$SECRET
host=dynamic
context=calico
callerid="${DISPLAY:-$NAME}" <$NUMBER>
disallow=all
allow=ulaw
allow=alaw

EOF
  i=$((i + 1))
done

echo "Calico Asterisk: wrote sip.conf ($(grep -c '^\[' "$CONFIG_DIR/sip.conf") sections)"

# =====================
# extensions.conf
# =====================
cat > "$CONFIG_DIR/extensions.conf" << EOF
; Auto-generated by entrypoint.sh — do not edit manually

[calico]

; Dial any registered extension directly
exten => _2XXX,1,Dial(SIP/\${EXTEN},30)
exten => _2XXX,2,Hangup()
EOF

echo "Calico Asterisk: wrote extensions.conf"

# =====================
# rtp.conf
# =====================
cat > "$CONFIG_DIR/rtp.conf" << EOF
; Auto-generated by entrypoint.sh — do not edit manually

[general]
rtpstart=${ASTERISK_RTP_START:-10000}
rtpend=${ASTERISK_RTP_END:-10100}
EOF

echo "Calico Asterisk: wrote rtp.conf"

# =====================
# modules.conf
# =====================
cat > "$CONFIG_DIR/modules.conf" << 'EOF'
; Auto-generated by entrypoint.sh — do not edit manually

[modules]
autoload=yes

noload => chan_dahdi.so
noload => chan_mgcp.so
noload => chan_skinny.so
noload => chan_unistim.so
noload => res_fax.so
EOF

echo "Calico Asterisk: wrote modules.conf"

# =====================
# manager.conf
# =====================
cat > "$CONFIG_DIR/manager.conf" << EOF
; Auto-generated by entrypoint.sh — do not edit manually

[general]
enabled=yes
port=${ASTERISK_AMI_PORT:-5038}
bindaddr=127.0.0.1

[${ASTERISK_AMI_USER:-calico}]
secret=${ASTERISK_AMI_SECRET}
permit=127.0.0.1/255.255.255.255
read=all
write=all
EOF

echo "Calico Asterisk: wrote manager.conf"
echo "Calico Asterisk: starting..."

exec asterisk -f
